#!/bin/bash

# Путь до директории ЕСС
path=/home/savinov/ess

# Название тикета
ticket=$1

# Отобразить название ветки
function getBranch {
    cd $path/$1/
    branch=$(git symbolic-ref --short HEAD)
    echo "$1 ---> $branch"
}

# Перейти на ветку тикета, если такой существует, иначе переходить на ветку master
function switchBranch {
    cd $path/$1/
    git reset HEAD --hard
    git fetch
    if [[ -z $(git branch -a | grep "$ticket") ]]
    then
        echo "-------------------------------------------------------"
        echo "$1 doesn't have branch $ticket, switching to master..."
        echo "-------------------------------------------------------"
        git checkout master
    else
        echo "-------------------------------------------------------"
        echo "          switching to $ticket on $(pwd)" 
        echo "-------------------------------------------------------"
        git checkout $ticket
    fi
    git pull
 getBranch $1
}
